services:
  - type: web
    name: station-challenge-2026
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
    disk:
      name: station-data
      mountPath: /opt/render/project/src/server
      sizeGB: 1
